-- Drop tables in reverse order
DROP TABLE IF EXISTS "LeadAssignments" CASCADE;
DROP TABLE IF EXISTS "Leads" CASCADE;
DROP TABLE IF EXISTS "Orders" CASCADE;
DROP TABLE IF EXISTS "Plans" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
